from __future__ import annotations

import hashlib
import os
from pathlib import Path
from typing import Any, Dict, Iterable, List, Set

from .store import MemoryStore, normalize_whitespace, pretty_topic, slugify

MANAGED_SUBDIRS = ("topics", "sessions", "preferences", "policies", "contradictions")


def _safe_page_name(value: str, *, fallback: str) -> str:
    clean = normalize_whitespace(value)
    slug = slugify(clean) if clean else fallback
    digest = hashlib.sha1(clean.encode("utf-8")).hexdigest()[:8] if clean else "00000000"
    return f"{slug}-{digest}.md"


def _normalize_markdown(text: str) -> str:
    clean = str(text or "").replace("\r\n", "\n").strip()
    return clean + "\n"


def _write_if_changed(path: Path, content: str) -> bool:
    normalized = _normalize_markdown(content)
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if current == normalized:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(normalized, encoding="utf-8")
    return True


def _relative_link(from_rel: str, to_rel: str) -> str:
    return Path(os.path.relpath(to_rel, start=str(Path(from_rel).parent))).as_posix()


def _bullet_link(label: str, target_rel: str, *, from_rel: str) -> str:
    return f"[{label}]({_relative_link(from_rel, target_rel)})"


def _fmt_ts(value: Any) -> str:
    try:
        ts = float(value or 0)
    except Exception:
        return ""
    if ts <= 0:
        return ""
    import time

    return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(ts))


def _render_index(
    *,
    counts: Dict[str, int],
    topics: List[Dict[str, Any]],
    sessions: List[Dict[str, Any]],
    preferences: List[Dict[str, Any]],
    policies: List[Dict[str, Any]],
    contradictions: List[Dict[str, Any]],
    topic_paths: Dict[str, str],
    session_paths: Dict[str, str],
) -> str:
    rel = "index.md"
    lines = [
        "# Compiled Memory Wiki",
        "",
        "> Generated by `consolidating_local`. Edit the SQLite source of truth, not these files.",
        "",
        "## Snapshot",
        "",
        f"- Facts: {counts.get('facts', 0)}",
        f"- Topics: {counts.get('topics', 0)}",
        f"- Sessions: {counts.get('sessions', 0)}",
        f"- Summaries: {counts.get('summaries', 0)}",
        f"- Preferences: {counts.get('preferences', 0)}",
        f"- Policies: {counts.get('policies', 0)}",
        f"- Contradictions: {counts.get('contradictions', 0)}",
        "",
        "## Top Topics",
        "",
    ]
    if topics:
        for topic in topics[:10]:
            target = topic_paths.get(str(topic.get("slug") or ""))
            if not target:
                continue
            lines.append(f"- {_bullet_link(str(topic.get('title') or pretty_topic(str(topic.get('slug') or 'topic'))), target, from_rel=rel)}: {str(topic.get('summary') or '')}")
    else:
        lines.append("- No topics exported yet.")
    lines.extend(["", "## Latest Sessions", ""])
    if sessions:
        for session in sessions[:10]:
            session_id = str(session.get("session_id") or "")
            target = session_paths.get(session_id)
            if not target:
                continue
            summary = normalize_whitespace(str(session.get("summary") or "")) or "No summary yet."
            lines.append(f"- {_bullet_link(session_id, target, from_rel=rel)}: {summary}")
    else:
        lines.append("- No session pages exported yet.")
    lines.extend(["", "## Active Preferences", ""])
    if preferences:
        for item in preferences[:10]:
            lines.append(f"- {str(item.get('content') or item.get('label') or '')}")
    else:
        lines.append("- No active preferences.")
    lines.extend(["", "## Active Policies", ""])
    if policies:
        for item in policies[:10]:
            lines.append(f"- {str(item.get('content') or item.get('label') or '')}")
    else:
        lines.append("- No active policies.")
    lines.extend(["", "## Recent Contradictions", ""])
    if contradictions:
        for row in contradictions[:10]:
            winner = normalize_whitespace(str(row.get("winner_content") or ""))
            loser = normalize_whitespace(str(row.get("loser_content") or ""))
            lines.append(f"- {str(row.get('subject_key') or 'unknown')}: {loser} -> {winner}")
    else:
        lines.append("- No contradictions logged.")
    return "\n".join(lines)


def _render_topic_page(
    topic: Dict[str, Any],
    *,
    facts: List[Dict[str, Any]],
    contradictions: List[Dict[str, Any]],
    session_paths: Dict[str, str],
) -> str:
    rel = f"topics/{topic['slug']}.md"
    title = str(topic.get("title") or pretty_topic(str(topic.get("slug") or "topic")))
    lines = [
        f"# {title}",
        "",
        f"- Slug: `{str(topic.get('slug') or '')}`",
        f"- Category: `{str(topic.get('category') or 'general')}`",
        f"- Salience: {float(topic.get('salience') or 0.0):.2f}",
        f"- Updated: {_fmt_ts(topic.get('updated_at')) or 'unknown'}",
        "",
        "## Summary",
        "",
        str(topic.get("summary") or "No summary available."),
        "",
        "## Supporting Facts",
        "",
    ]
    if facts:
        for fact in facts:
            lines.append(f"- {str(fact.get('content') or '')}")
    else:
        lines.append("- No supporting facts linked.")
    lines.extend(["", "## Related Sessions", ""])
    seen_sessions: Set[str] = set()
    session_lines: List[str] = []
    for fact in facts:
        session_id = str(fact.get("source_session_id") or "")
        target = session_paths.get(session_id)
        if not session_id or not target or session_id in seen_sessions:
            continue
        seen_sessions.add(session_id)
        session_lines.append(f"- {_bullet_link(session_id, target, from_rel=rel)}")
    if session_lines:
        lines.extend(session_lines)
    else:
        lines.append("- No related session pages.")
    lines.extend(["", "## Contradictions", ""])
    topic_contradictions = [
        row for row in contradictions if str(row.get("winner_topic") or "") == str(topic.get("slug") or "") or str(row.get("loser_topic") or "") == str(topic.get("slug") or "")
    ]
    if topic_contradictions:
        for row in topic_contradictions[:10]:
            winner = normalize_whitespace(str(row.get("winner_content") or ""))
            loser = normalize_whitespace(str(row.get("loser_content") or ""))
            lines.append(f"- {str(row.get('subject_key') or 'unknown')}: {loser} -> {winner}")
    else:
        lines.append("- No contradictions for this topic.")
    lines.extend(
        [
            "",
            "## Backlinks",
            "",
            f"- [Compiled Memory Wiki]({_relative_link(rel, 'index.md')})",
            f"- [Contradiction Index]({_relative_link(rel, 'contradictions/index.md')})",
        ]
    )
    return "\n".join(lines)


def _render_session_page(
    session: Dict[str, Any],
    *,
    artifacts: Dict[str, Any],
    topic_paths: Dict[str, str],
) -> str:
    session_id = str(session.get("session_id") or "")
    rel = f"sessions/{_safe_page_name(session_id, fallback='session')}"
    lines = [
        f"# Session {session_id}",
        "",
        f"- Status: `{str(session.get('status') or 'unknown')}`",
        f"- Started: {_fmt_ts(session.get('started_at')) or 'unknown'}",
        f"- Ended: {_fmt_ts(session.get('ended_at')) or 'open'}",
        f"- Last activity: {_fmt_ts(session.get('last_activity_at')) or 'unknown'}",
        "",
        "## Summary",
        "",
        str(session.get("summary") or "No session summary available."),
        "",
        "## Facts",
        "",
    ]
    facts = list(artifacts.get("facts", []))
    if facts:
        for fact in facts:
            topic_slug = str(fact.get("topic") or "")
            topic_target = topic_paths.get(topic_slug)
            suffix = f" ({_bullet_link(pretty_topic(topic_slug), topic_target, from_rel=rel)})" if topic_target else ""
            lines.append(f"- {str(fact.get('content') or '')}{suffix}")
    else:
        lines.append("- No extracted facts linked to this session.")
    lines.extend(["", "## Preferences", ""])
    preferences = list(artifacts.get("preferences", []))
    if preferences:
        for item in preferences:
            lines.append(f"- {str(item.get('content') or item.get('label') or '')}")
    else:
        lines.append("- No session-specific preferences.")
    lines.extend(["", "## Policies", ""])
    policies = list(artifacts.get("policies", []))
    if policies:
        for item in policies:
            lines.append(f"- {str(item.get('content') or item.get('label') or '')}")
    else:
        lines.append("- No session-specific policies.")
    lines.extend(["", "## Journals", ""])
    journals = list(artifacts.get("journals", []))
    if journals:
        for item in journals:
            lines.append(f"- {str(item.get('label') or 'Journal')}: {str(item.get('content') or '')}")
    else:
        lines.append("- No journals for this session.")
    lines.extend(["", "## Traces", ""])
    traces = list(artifacts.get("traces", []))
    if traces:
        for item in traces[:10]:
            lines.append(f"- {str(item.get('content') or '')}")
    else:
        lines.append("- No traces for this session.")
    lines.extend(["", "## Backlinks", ""])
    linked_topics: List[str] = []
    for fact in facts:
        topic_slug = str(fact.get("topic") or "")
        topic_target = topic_paths.get(topic_slug)
        if not topic_target or topic_slug in linked_topics:
            continue
        linked_topics.append(topic_slug)
        lines.append(f"- {_bullet_link(pretty_topic(topic_slug), topic_target, from_rel=rel)}")
    if not linked_topics:
        lines.append("- No linked topic pages.")
    lines.append(f"- [Compiled Memory Wiki]({_relative_link(rel, 'index.md')})")
    return "\n".join(lines)


def _render_preferences_index(
    preferences: List[Dict[str, Any]],
    *,
    session_paths: Dict[str, str],
) -> str:
    rel = "preferences/index.md"
    lines = [
        "# Preferences",
        "",
        "> Generated index of active durable preferences.",
        "",
    ]
    if preferences:
        for item in preferences:
            session_id = str(item.get("source_session_id") or dict(item.get("metadata") or {}).get("session_id") or "")
            session_suffix = ""
            if session_id and session_id in session_paths:
                session_suffix = f" ({_bullet_link(session_id, session_paths[session_id], from_rel=rel)})"
            lines.append(f"- **{str(item.get('label') or item.get('preference_key') or 'Preference')}**: {str(item.get('value') or item.get('content') or '')}{session_suffix}")
    else:
        lines.append("- No active preferences.")
    lines.extend(["", f"- [Compiled Memory Wiki]({_relative_link(rel, 'index.md')})"])
    return "\n".join(lines)


def _render_policies_index(
    policies: List[Dict[str, Any]],
    *,
    session_paths: Dict[str, str],
) -> str:
    rel = "policies/index.md"
    lines = [
        "# Policies",
        "",
        "> Generated index of active workflow rules and operating constraints.",
        "",
    ]
    if policies:
        for item in policies:
            session_id = str(item.get("source_session_id") or dict(item.get("metadata") or {}).get("session_id") or "")
            session_suffix = ""
            if session_id and session_id in session_paths:
                session_suffix = f" ({_bullet_link(session_id, session_paths[session_id], from_rel=rel)})"
            lines.append(f"- **{str(item.get('label') or item.get('policy_key') or 'Policy')}**: {str(item.get('content') or '')}{session_suffix}")
    else:
        lines.append("- No active policies.")
    lines.extend(["", f"- [Compiled Memory Wiki]({_relative_link(rel, 'index.md')})"])
    return "\n".join(lines)


def _render_contradictions_index(contradictions: List[Dict[str, Any]]) -> str:
    rel = "contradictions/index.md"
    lines = [
        "# Contradictions",
        "",
        "> Generated changelog of superseded assumptions.",
        "",
    ]
    if contradictions:
        for row in contradictions:
            winner = normalize_whitespace(str(row.get("winner_content") or ""))
            loser = normalize_whitespace(str(row.get("loser_content") or ""))
            created = _fmt_ts(row.get("created_at")) or "unknown"
            lines.append(f"- **{str(row.get('subject_key') or 'unknown')}** ({created}): {loser} -> {winner}")
    else:
        lines.append("- No contradictions logged.")
    lines.extend(["", f"- [Compiled Memory Wiki]({_relative_link(rel, 'index.md')})"])
    return "\n".join(lines)


def export_compiled_wiki(
    store: MemoryStore,
    *,
    export_dir: str | Path,
    session_limit: int = 50,
    topic_limit: int = 100,
) -> Dict[str, Any]:
    root = Path(export_dir).expanduser()
    root.mkdir(parents=True, exist_ok=True)

    topics = store.list_topics(limit=topic_limit)
    sessions = store.list_sessions(limit=session_limit)
    preferences = store.list_preferences(limit=200)
    policies = store.list_policies(limit=200)
    contradictions = store.recent_contradictions(limit=200)
    counts = store.counts()

    topic_paths = {str(topic.get("slug") or ""): f"topics/{str(topic.get('slug') or '')}.md" for topic in topics if topic.get("slug")}
    session_paths = {
        str(session.get("session_id") or ""): f"sessions/{_safe_page_name(str(session.get('session_id') or ''), fallback='session')}"
        for session in sessions
        if session.get("session_id")
    }

    expected: Dict[str, str] = {}
    expected["index.md"] = _render_index(
        counts=counts,
        topics=topics,
        sessions=sessions,
        preferences=preferences,
        policies=policies,
        contradictions=contradictions,
        topic_paths=topic_paths,
        session_paths=session_paths,
    )
    expected["preferences/index.md"] = _render_preferences_index(preferences, session_paths=session_paths)
    expected["policies/index.md"] = _render_policies_index(policies, session_paths=session_paths)
    expected["contradictions/index.md"] = _render_contradictions_index(contradictions)

    for topic in topics:
        slug = str(topic.get("slug") or "")
        if not slug:
            continue
        expected[f"topics/{slug}.md"] = _render_topic_page(
            topic,
            facts=store.topic_supporting_facts(int(topic["id"]), limit=20),
            contradictions=contradictions,
            session_paths=session_paths,
        )

    for session in sessions:
        session_id = str(session.get("session_id") or "")
        if not session_id:
            continue
        rel = session_paths[session_id]
        expected[rel] = _render_session_page(
            session,
            artifacts=store.get_session_artifacts(session_id, limit=20),
            topic_paths=topic_paths,
        )

    written = 0
    for rel, content in sorted(expected.items()):
        if _write_if_changed(root / rel, content):
            written += 1

    for subdir in MANAGED_SUBDIRS:
        (root / subdir).mkdir(parents=True, exist_ok=True)

    existing_files: Set[str] = set()
    if (root / "index.md").exists():
        existing_files.add("index.md")
    for subdir in MANAGED_SUBDIRS:
        base = root / subdir
        if not base.exists():
            continue
        for file_path in sorted(base.rglob("*.md")):
            existing_files.add(file_path.relative_to(root).as_posix())

    expected_paths = set(expected.keys())
    stale_paths = sorted(existing_files - expected_paths)
    for rel in stale_paths:
        stale_file = root / rel
        if stale_file.exists():
            stale_file.unlink()

    return {
        "root": str(root),
        "generated_files": len(expected_paths),
        "written_files": int(written),
        "pruned_files": len(stale_paths),
        "topic_pages": len(topics),
        "session_pages": len(sessions),
        "index_files": 4,
    }
